server:
  host: "0.0.0.0"
  port: 8080
  mode: "development"
  appVersion: "0.0.1"
  secret: "1234568"
  authExpMinute: 30
  authRefreshMinute: 180
  mailPass: "nvha zimc lusz mlxj"
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "survey_db"
  SslMode: "disable"
logger:
  level: "info"
  encoding: "json"
  path: "./log.log"
