server:
  host: "0.0.0.0"
  port: 8080
  mode: "development"
  appVersion: "0.0.1"
  secret: "abc"
  authExpMinute: 30
  authRefreshMinute: 180
  mailPass: "pass"
  fromMail: "youremail@gmail.com"
  meiliSearchHost: "http://meilisearch:7700"
  maxSecondForChangeBirthdate: 99400

postgres:
  host: db
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "survey_db"
  SslMode: "disable"
logger:
  level: "info"
  encoding: "json"
  path: "sample-log.log"