server:
  host: "127.0.0.1"
  port: "8080"
  mode:
  appVersion:
  MailPass: "pass"
  FromMail: "youremail@gmail.com"
  Secret: "abc"
  AuthExpMinute: 600
  AuthRefreshMinute: 1200
  MaxSecondForChangeBirthdate: 99400
postgres:
  host: "127.0.0.1"
  port: "5432"
  user: "postgres"
  password:
  dbname: "golang_test"
  SslMode: "disable"
logger:
  level:
  encoding:
  path: "./log.log"
