server:
  host: "0.0.0.0"
  port: 8080
  mode: "development"
  appVersion: "0.0.1"
  secret:
  authExpMinute: 30
  authRefreshMinute: 180
  senderMail: "email@address.com"
  mailPass:
  meiliSearchHost: "http://meilisearch:7700"

postgres:
  host: db
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "survey_db"
  SslMode: "disable"
  clean: false
logger:
  level: "info"
  encoding: "json"
  path: "sample-log.log"
