server:
  host:
  port:
  mode:
  appVersion:
  secret:
  authExpMin:
  authExpRefreshMin:
  mailPass:
postgres:
  host:
  port:
  user:
  password:
  dbname:
  SslMode:
logger:
  level:
  encoding:
  path:
