server:
  host: "0.0.0.0"
  port: 8080
  mode: "development"
  appVersion: "0.0.1"
postgres:
  host: localhost
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "survey_db"
  SslMode: false
logger:
  level: "info"
  encoding: "json"
  path: "app.log"
