services:
  elk:
    image: sebp/elk
    container_name: elk
    ports:
      - "5601:5601"  # Kibana
      - "9200:9200"  # Elasticsearch
      - "5044:5044"  # Logstash
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"  # Adjust JVM heap size for Elasticsearch
    volumes:
      - elk-data:/var/lib/elasticsearch  # Persistent storage for Elasticsearch data
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=survey_db sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: survey_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  elk-data:
