services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=survey_db sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - db


  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: survey_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
