services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=db user=postgres password=postgres dbname=survey_db sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - loki

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: survey_db
    volumes:
      - db_data:/var/lib/postgresql/data

  loki:
    image: grafana/loki
    volumes:
      - /home/meiti/Projects/magic-survey/deploy/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
  promtail:
    image: grafana/promtail
    volumes:
      - /var/log:/var/log
      - /home/meiti/Projects/magic-survey/deploy/promtail:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
  grafana:
    image: grafana/grafana
    user: "1000"
    volumes:
      - /home/meiti/Projects/magic-survey/deploy/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki

volumes:
  db_data:
  grafana-data:
  loki-data:

networks:
  loki: