services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=db user=postgres password=postgres dbname=survey_db sslmode=disable"
      MEILISEARCH_HOST: "http://meilisearch:7700"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - meilisearch

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: survey_db
    volumes:
      - db_data:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:v1.2.0 # Replace with the latest version if necessary
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "wf_4gRrCDLEh58UYAALQgoUuVQoH2b2HQpsNTi75oK4"
    volumes:
      - meilisearch-data:/meili_data

volumes:
  db_data:
  meilisearch-data:

networks:
  loki:
