server:
  host: localhost
  port: 8080
  mode:
  appVersion:
postgres:
  host: 0.0.0.0
  port: 5432
  user: postgres
  password: 123456
  dbname: test
  SslMode: disable
logger:
  level:
  encoding:
  path: "./log"
